---
- name: Create directory
  become: true
  ansible.builtin.file:
    path: /{{ env }}-webdir/{{ username }}
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Add entry to /etc/fstab
  become: true
  ansible.posix.mount:
    fstype: nfs
    opts: defaults
    dump: 0
    passno: 0
    state: mounted
    src: "{{ efs_source }}"
    path: /{{ env }}-webdir/{{ username }}
