- name: Check if {{ project_folder }} folder exist
  stat:
    path: "/{{ env }}-webdir/{{ username }}/public_html/{{ project_name }}"
  register: project_folder
  tags: wordpress

- name: change Folder Owner
  file:
    path: /{{ env }}-webdir/{{ username }}/public_html
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: laravel

- name: Add WP-Config
  become: true
  template:
    src: "wp-config.php.j2"
    dest: "/{{ env }}-webdir/{{ username }}/public_html/{{ project_name }}/public/wp-config.php"
    owner: "{{ username }}"
  tags: wordpress

- name: Add htaccess
  become: true
  copy:
    owner: "{{ username }}"
    src: "htaccess.txt"
    dest: "/{{ env }}-webdir/{{ username }}/public_html/{{ project_name }}/public/.htaccess"
  tags: wordpress
