- name: Create a VirtualHost
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ username }}.conf
  notify:
    - restart_apache
  tags: apache

- name: Enable the VirtualHost
  file:
    src: /etc/apache2/sites-available/{{ username }}.conf
    dest: /etc/apache2/sites-enabled/{{ username }}.conf
    state: link
  notify:
    - restart_apache
  tags: apache
