---
- name: Install Mod Security
  apt:
    name: libapache2-mod-security2
    state: present
  tags: apache

- name: Enable Mod Security
  community.general.apache2_module:
    state: present
    name: "security2"
  notify: restart_apache
  tags: apache

- name: Enable Mod-Security Recommended Settings
  file:
    src: /etc/modsecurity/modsecurity.conf-recommended
    dest: /etc/modsecurity/modsecurity.conf
    remote_src: true
  notify: restart_apache
  tags: apache

- name: Update the Settings
  replace:
    path: /etc/modsecurity/modsecurity.conf
    regexp: "{{ item.old }}"
    replace: "{{ item.new }}"
    backup: yes
  loop:
    - old: "SecRuleEngine DetectionOnly"
      new: "SecRuleEngine On"
    - old: "SecAuditLogParts ABDEFHIJZ"
      new: "SecAuditLogParts ABCEFHJKZ"
  notify: restart_apache
  tags: apache

- name: Download OWASP Filter
  become_user: "{{ username }}"
  get_url:
    url: https://github.com/coreruleset/coreruleset/archive/refs/tags/v{{ crs_version }}.zip
    dest: /home/{{ username }}/coreruleset-{{ crs_version }}.zip
  tags: apache

- name: Extract the latest filter
  become_user: "{{ username }}"
  unarchive:
    src: /home/{{ username }}/coreruleset-{{ crs_version }}.zip
    dest: /home/{{ username }}/coreruleset-{{ crs_version }}
    remote_src: true
  ignore_errors: true
  tags: apache

- name: Create CRS directory
  become: true
  file:
    path: /etc/apache2/modsecurity-crs/
    state: directory
  tags: apache

- name: Copy OWAS Filter to CRS directory
  copy:
    src: /home/{{ username }}/coreruleset-{{ crs_version }}
    dest: /etc/apache2/modsecurity-crs/
  tags: apache

- name: Enable OWASP Filter
  copy:
    src: /etc/apache2/modsecurity-crs/coreruleset-{{ crs_version }}/crs-setup.conf.example
    dest: /etc/apache2/modsecurity-crs/coreruleset-{{ crs_version }}/crs-setup.conf

- name: Activate OWASP Filter
  replace:
    path: /etc/apache2/mods-enabled/security2.conf
    regexp: "IncludeOptional /usr/share/modsecurity-crs/*.load"
    replace: |-
      IncludeOptional /etc/apache2/modsecurity-crs/coreruleset-{{ crs_version }}/crs-setup.conf
      IncludeOptional /etc/apache2/modsecurity-crs/coreruleset-{{ crs_version }}/rules/*.conf
    backup: yes
  notify: restart_apache
  tags: apache
