- name: Clone a private repository into {{ project_name }} folder.
  become: false
  git:
    repo: "{{ git_repo }}"
    version: "{{ git_branch }}"
    dest: "/home/ubuntu/public_html/{{ project_name }}"
    accept_hostkey: yes
  tags: php

- name: Delete main directiry
  become: true
  file:
    state: absent
    path: /home/ubuntu/{{ project_name }}
  tags: php

- name: Change Folder Owner
  file:
    path: /home/{{ username }}/public_html
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: laravel

- name: Add htaccess
  become: true
  copy:
    owner: "{{ username }}"
    src: "htaccess.txt"
    dest: "/home/{{ username }}/public_html/{{ project_name }}/.htaccess"
  tags: php
