---
- name: Create a user
  ansible.builtin.user:
    name: "{{ username }}"
    append: true
    generate_ssh_key: true
    shell: /bin/bash
  become: true
  tags: common

- name: Add user to sudoers
  community.general.sudoers:
    name: "{{ username }}"
    user: "{{ username }}"
    commands: ALL
  tags: common

- name: Create a DocumentRoot
  ansible.builtin.file:
    path: /home/{{ username }}/public_html
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  tags: common

- name: Create a apache_logs folder
  ansible.builtin.file:
    path: /home/{{ username }}/apache_logs
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  tags: common
