- name: Allow connections on port 80
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    state: NEW
    jump: ACCEPT
    insert_before: 6
  tags: common

- name: "Make the table persistent"
  become: true
  command: "netfilter-persistent save"
  tags: common
