- name: Allow connections on port 80
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    ctstate: NEW
    destination_ports:
      - "80"
    jump: ACCEPT
  tags: common

- name: "Make the table persistent"
  become: true
  command:
    cmd: "sudo netfilter-persistent save"
  tags: common
