---
- name: Allow connections on port 80
  become: true
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    ctstate: NEW
    jump: ACCEPT
    state: present
  tags: common
  register: output

- name: Make the table persistent
  become: true
  ansible.builtin.command: netfilter-persistent save
  tags: common
  changed_when: my_output.rc != 0
