---
- name: Create a .ssh folder
  become: true
  ansible.builtin.file:
    path: /home/ubuntu/.ssh
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: "0755"
  tags: common

- name: Create a .ssh folder
  become: true
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  tags: common

- name: Install Masterkey Public Key
  become: true
  ansible.builtin.copy:
    owner: ubuntu
    group: ubuntu
    src: id_rsa.pub
    dest: /home/ubuntu/.ssh/id_rsa.pub
    mode: "0600"
  tags: common

- name: Install Masterkey Public Key
  become: true
  ansible.builtin.copy:
    owner: "{{ username }}"
    group: "{{ username }}"
    src: id_rsa.pub
    dest: /home/{{ username }}/.ssh/id_rsa.pub
    mode: "0600"
  tags: common

- name: Install Masterkey Private Key
  become: true
  ansible.builtin.copy:
    owner: ubuntu
    group: ubuntu
    src: id_rsa
    dest: /home/ubuntu/.ssh/id_rsa
    mode: "0600"
  tags: common

- name: Install Masterkey Private Key
  become: true
  ansible.builtin.copy:
    owner: "{{ username }}"
    group: "{{ username }}"
    src: id_rsa
    dest: /home/{{ username }}/.ssh/id_rsa
    mode: "0600"
  tags: common
