---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  tags: common

- name: Install Zip & Unzip
  ansible.builtin.apt:
    name:
      - zip
      - unzip
    state: present
  tags: common
