- name: Update apt cache
  apt:
    update_cache: yes
  tags: common

- name: Install Redis Server
  apt:
    name: redis-server
    state: latest
  tags: common

- name: Configure fpm/php.ini file
  lineinfile:
    path: "/etc/redis/redis.conf"
    regexp: "{{ item.parameter }} "
    line: "{{ item.parameter }} {{ item.value }}"
    backup: yes
  with_items:
    - parameter: maxmemory
      value: "256mb"
    - parameter: maxmemory-policy
      value: "allkeys-lru"
  notify:
    - restart_php
    - restart_nginx
    - restart_redis
  tags: common

- name: Install PHP-Redis
  apt:
    name: php8.2-redis
    state: latest
  tags: common

- name: Enable Redis
  become: true
  shell: "phpenmod -v 8.2 -s ALL redis"
  notify:
    - restart_php
    - restart_nginx
    - restart_redis
  tags: common
