- name: Configure fpm/php.ini file
  lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "{{ item.parameter }} ="
    line: "{{ item.parameter }} = {{ item.value }}"
    backup: yes
  with_items:
    - parameter: post_max_size
      value: "{{ post_max_size }}"
    - parameter: upload_max_filesize
      value: "{{ upload_max_filesize }}"
    - parameter: max_execution_time
      value: "{{ max_execution_time }}"
    - parameter: max_input_time
      value: "{{ max_input_time }}"
    - parameter: memory_limit
      value: "{{ memory_limit }}"
  notify:
    - restart_php
    - restart_apache
  tags: common
