---
- name: Clear Routes Cache
  ansible.builtin.command: php artisan routes:clear
  register: my_output
  changed_when: my_output.rc != 0
  tags: laravel

- name: Clear Application Cache
  ansible.builtin.command: php artisan cache:clear
  register: my_output
  changed_when: my_output.rc != 0
  tags: laravel

- name: Clear Views Cache
  ansible.builtin.command: php artisan cache:clear
  register: my_output
  changed_when: my_output.rc != 0
  tags: laravel
