---
- name: Clear Routes Cache
  php_artisan:
    command: route:clear
    artisan_path: /home/{{ username }}/public_html/artisan
    working_dir: /home/{{ username }}/public_html
  tags: laravel

- name: Clear Application Cache
  php_artisan:
    command: cache:clear
    artisan_path: /home/{{ username }}/public_html/artisan
    working_dir: /home/{{ username }}/public_html
  tags: laravel

- name: Clear Views Cache
  php_artisan:
    command: view:clear
    artisan_path: /home/{{ username }}/public_html/artisan
    working_dir: /home/{{ username }}/public_html
  tags: laravel
