- name: Clear Routes Cache
  command: "php artisan routes:clear"
  tags: laravel

- name: Clear Application Cache
  command: "php artisan cache:clear"
  tags: laravel

- name: Clear Views Cache
  command: "php artisan cache:clear"
  tags: laravel
