- name: Check if {{ project_folder }} folder exist
  stat:
    path: "/home/{{ username }}/public_html/{{ project_name }}"
  register: project_folder
  tags: laravel

- name: Clone a private repository into {{ project_name }} folder.
  become: false
  git:
    repo: "{{ git_repo }}"
    version: "{{ git_branch }}"
    dest: "/home/{{ username }}/public_html/{{ project_name }}"
    accept_hostkey: yes
    when: not project_folder.state.exist
  tags: laravel

- name: change Folder Owner
  file:
    path: /home/{{ username }}/public_html
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
  when: project_folder.state.exist
  tags: laravel

- name: Install laravel dependencies
  community.general.composer:
    command: install
    working_dir: "/home/{{ username }}/public_html/{{ project_name }}"
  become: true
  become_user: "{{ username }}"
  tags: laravel

- name: Copy env file
  template:
    src: env.j2
    dest: /home/{{ username }}/public_html/{{ project_name }}/.env
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
  become: true
  when: project_folder.state.exist
  tags: laravel

- name: Setup laravel
  command: php artisan key:generate
  args:
    chdir: "/home/{{ username }}/public_html/{{ project_name }}"
  become: true
  when: project_folder.state.exist
  tags: laravel

- name: Add htaccess
  become: true
  copy:
    owner: "{{ username }}"
    src: "htaccess.txt"
    dest: "/home/{{ username }}/public_html/{{ project_name }}/.htaccess"
  when: project_folder.state.exist
  tags: laravel
