---
- name: Install laravel dependencies
  community.general.composer:
    command: install
    working_dir: /home/{{ username }}/public_html/
  become: true
  become_user: "{{ username }}"
  when: project_folder.state.exists
  tags: laravel

- name: Copy env file
  ansible.builtin.template:
    src: env.j2
    dest: /home/{{ username }}/public_html/.env
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
  become: true
  when: project_folder.state.exists
  tags: laravel

- name: Setup laravel
  block:
    - name: Generate Key
      php_artisan:
        command: key:generate
        artisan_path: /home/{{ username }}/public_html/artisan
        working_dir: /home/{{ username }}/public_html
      become: true
      when: project_folder.state.exists
      tags: laravel

    - name: Link Storage
      php_artisan:
        command: storage:link
        artisan_path: /home/{{ username }}/public_html/artisan
        working_dir: /home/{{ username }}/public_html
      become: true
      when: project_folder.state.exists
      tags: laravel

- name: Add htaccess
  become: true
  ansible.builtin.copy:
    owner: "{{ username }}"
    src: htaccess.txt
    dest: /home/{{ username }}/public_html/.htaccess
    mode: "0644"
  when: project_folder.state.exists
  tags: laravel
