---
- name: Install laravel
  community.general.composer:
    command: create-project
    arguments: laravel/laravel {{ project_name }}
    working_dir: /home/{{ username }}/public_html
    prefer_dist: true
  become: true
  become_user: "{{ username }}"

- name: Install laravel dependencies
  community.general.composer:
    command: install
    working_dir: /home/{{ username }}/public_html/{{ project_name }}
  become: true
  become_user: "{{ username }}"
  tags: laravel

- name: Copy env file
  ansible.builtin.template:
    src: env.j2
    dest: /home/{{ username }}/public_html/{{ project_name }}/.env
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
  become: true
  tags: laravel

- name: Setup laravel
  ansible.builtin.script: php artisan key:generate
  register: my_output
  args:
    chdir: /home/{{ username }}/public_html/{{ project_name }}
  become: true
  tags: laravel

- name: Add htaccess
  become: true
  ansible.builtin.copy:
    owner: "{{ username }}"
    src: htaccess.txt
    dest: /home/{{ username }}/public_html/public/{{ project_name }}/.htaccess
    mode: preserve
  tags: laravel
