---
- name: Install Composer
  ansible.builtin.include_tasks: install_composer.yml

- name: Deploy Laravel
  ansible.builtin.include_tasks: deploy_laravel.yml

- name: Clear Laravel Cache
  ansible.builtin.include_tasks: clean_laravel_cache.yml
