---
- name: Add WP-Config
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ apache_root_path }}/{{ project_name }}/public/wp-config.php"
    owner: "{{ username }}"
    mode: "0644"
  when: project_folder.state.exist
  tags: wordpress
