---
- name: Add WP-Config
  become: true
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ apache_root_path }}/public/wp-config.php"
    owner: "{{ username }}"
    mode: "0644"
  when: project_folder.state.exists
  tags: wordpress

- name: Add htaccess
  become: true
  ansible.builtin.copy:
    owner: "{{ username }}"
    src: htaccess.txt
    dest: "{{ apache_root_path }}/public/.htaccess"
    mode: "0644"
  when: project_folder.stat.exists
  tags: wordpress
