---
- name: Check if folder exist {{ project_name }}
  ansible.builtin.stat:
    path: "{{ apache_root_path }}/{{ project_name }}"
  register: project_folder
  tags: wordpress

- name: Clone a private repository into {{ project_name }}.
  become: true
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    version: "{{ git_branch }}"
    dest: "{{ apache_root_path }}/{{ project_name }}"
    accept_hostkey: true
  when: not project_folder.stat.exists
  tags: wordpress

- name: Change Folder Owner
  ansible.builtin.file:
    path: "{{ apache_root_path }}"
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: laravel

- name: Add WP-Config
  ansible.builtin.import_tasks: add_wp_config.yml

- name: Add htaccess
  become: true
  ansible.builtin.copy:
    owner: "{{ username }}"
    src: htaccess.txt
    dest: "{{ apache_root_path }}/{{ project_name }}/public/.htaccess"
    mode: "0644"
  when: project_folder.stat.exists
  tags: wordpress
