---
# WordPress Configuration

- name: Download and unpack latest WordPress
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "{{ apache_root_path }}/"
    remote_src: true
    creates: "{{ apache_root_path }}/wordpress"
  tags: wordpress

- name: Rename WordPress to public
  ansible.builtin.file:
    src: "{{ apache_root_path }}/wordpress"
    dest: "{{ apache_root_path }}/public"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  tags: wordpress

- name: Set ownership
  ansible.builtin.file:
    path: "{{ apache_root_path }}/"
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: wordpress

- name: Set permissions for directories
  ansible.builtin.file:
    path: "{{ apache_root_path }}/public/"
    state: directory
    mode: "0750"
    recurse: true
  tags: wordpress

- name: Set permissions for files
  ansible.builtin.file:
    path: "{{ apache_root_path }}/public/"
    state: file
    mode: "0640"
    recurse: true
  tags: wordpress

- name: Set up wp-config
  ansible.builtin.copy:
    src: "{{ apache_root_path }}/public/wp-config-sample.php"
    dest: "{{ apache_root_path }}/public/wp-config.php"
    remote_src: true
    mode: "0644"
  tags: wordpress
