---
plugin: oracle.oci.oci

# Optional fields to specify oci connection config:

config_file: ~/.oci/config
config_profile: DEFAULT

# Set hostname format preferences

hostname_format_preferences:
  - private_ip

# Cache settings

cache: true
cache_plugin: jsonfile
cache_timeout: 7200
cache_connection: /tmp/oci_inventory
cache_prefix: oci
