---
# handlers file for common
- name: restart_apache
  tags: apache,debian,httpd
  service:
    name: apache2
    state: restarted
  listen: "restart_apache"

- name: restart_nginx
  tags: apache,debian,httpd
  service:
    name: nginx
    state: restarted
  listen: "restart_nginx"

- name: restart_php
  tags: php,debian
  service:
    name: php{{ php_version }}-fpm
    state: restarted
  listen: "restart_php"

- name: restart_redis
  tags: php,debian
  service:
    name: redis-server
    state: restarted
  listen: "restart_redis"
