---
- name: Download Azure DevOps Agent
  become: true
  become_user: "{{ agent_user }}"
  azure_devops:
    action: download
    agent_download_url: "{{ azuredevops_agent_download_url }}"
    agent_installation_directory: "{{ azuredevops_agent_installation_directory }}"
    agent_version: "{{ azuredevops_agent_version }}"
  failed_when: false
  tags: azuredevops

- name: Configure Azure DevOps Agent
  ansible.builtin.include_tasks: configure_azagent.yml

- name: Start Agent
  become_user: "{{ agent_user }}"
  become: true
  become_method: ansible.builtin.sudo
  azure_devops:
    action: start
    agent_user: "{{ agent_user }}"
    agent_installation_directory: "{{ azuredevops_agent_installation_directory }}"
  failed_when: false
  tags: azuredevops
