---
- name: Update Azure DevOps PAT
  become: true
  become_user: "{{ agent_user }}"
  become_method: ansible.builtin.sudo
  azure_devops:
    action: update
    agent_user: "{{ agent_user }}"
    agent_installation_directory: "{{ azuredevops_agent_installation_directory }}"
    organization_name: "{{ azuredevops_organization_name }}"
    orgnization_url: "{{ azuredevops_orgnization_url }}"
    agent_name: "{{ agent_name }}"
    agent_token: "{{ agent_token }}"
    agent_work_directory: "{{ agent_work_directory }}"
    agent_version: "{{ azuredevops_agent_version }}"
    agent_deployment_group_name: "{{ agent_deployment_group_name }}"
    agenet_deployment_group_project_name: "{{ agenet_deployment_group_project_name }}"
  register: update_result
  failed_when: update_result.rc != 0
  tags: azuredevops
