---
# tasks file for mysql
- name: Installing Mysql  and dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    - libmysqlclient-dev
  become: true
  tags: mysql

- name: start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes
  tags: mysql

- name: creating mysql user
  mysql_user:
    name: "{{db_user}}"
    password: "{{db_pass}}"
    priv: "*.*:ALL"
    host: "%"
    state: present
  tags: mysql

- name: creating medium_db
  mysql_db:
    name: "{{db_name}}"
    state: present
  tags: mysql
