---
# vars file for logrotate
logrotate_confd:
  - path: "{{ username }}"
    conf: |
      /home/{{ username }}/public_html/public/wp-content/*.log {
          daily
          missingok
          rotate 3
          compress
          delaycompress
          notifempty
          create 666 {{ username }} {{ username }}
      }
