- name: Clone a private repository into {{ project_name }} folder.
  become: false
  git:
    repo: "{{ git_repo }}"
    version: "{{ git_branch }}"
    dest: "/home/ubuntu/{{ project_name }}"
    accept_hostkey: yes
  tags: php

- name: Move Repo to User
  become: true
  command: mv /home/ubuntu/{{ project_name }}/public /home/{{ username }}/public_html
  tags: php

- name: Move .git to User
  become: true
  command: mv /home/ubuntu/{{ project_name }}/.git /home/{{ username }}/public_html
  tags: php

- name: Delete main directiry
  become: true
  file:
    state: absent
    path: /home/ubuntu/{{ project_name }}
  tags: php

- name: Change Folder Owner
  become: true
  command: chown -R {{ username }}:{{ username }} /home/{{ username }}/public_html
  tags: php

- name: Add htaccess
  become: true
  copy:
    owner: "{{ username }}"
    src: "htaccess.txt"
    dest: "/home/{{ username }}/public_html/.htaccess"
  tags: php
