---
- name: Create user
  hosts: all
  vars_prompt:
    - name: "username"
      prompt: "Enter the username"
      private: false

  tasks:
    - name: Create a user
      ansible.builtin.user:
        name: "{{ username }}"
        append: true
        generate_ssh_key: true
        shell: /bin/bash
      become: true

    - name: Add user to sudoers
      community.general.sudoers:
        name: "{{ username }}"
        user: "{{ username }}"
        commands: ALL

    - name: Create a DocumentRoot
      ansible.builtin.file:
        path: /home/{{ username }}/public_html
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"

    - name: Create a apache_logs folder
      ansible.builtin.file:
        path: /home/{{ username }}/apache_logs
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"
