---
- name: Deploy WordPress
  hosts: all
  vars_prompt:
    # Linux user
    - name: "username"
      prompt: "Enter the username"
      private: false

    - name: "groupname"
      prompt: "Enter the groupname"
      private: false

    # Virtual host
    - name: "domainname"
      prompt: "Enter the domainname"
      private: false

    - name: "domainalias"
      prompt: "Enter the domainalias"
      private: false

    # Database
    - name: "wordpress_db_host"
      prompt: "Enter the database host"
      private: false

    - name: "wordpress_db_name"
      prompt: "Enter the database name"
      private: false

    - name: "wordpress_db_user"
      prompt: "Enter the database user"
      private: false

    - name: "wordpress_db_password"
      prompt: "Enter the database password"
      private: true

    - name: "wordpress_db_prefix"
      prompt: "Enter the database prefix"
      private: false
      default: "wp_"

    - name: "enable_debug_mode"
      prompt: "Enable debug mode?"
      private: false
      default: "false"

    # Project Repo
    - name: "git_repo"
      prompt: "Enter the git repository"
      private: false

    - name: "git_branch"
      prompt: "Enter the git branch"
      private: false

    - name: "git_project_name"
      prompt: "Enter the project name"
      private: false

  vars_files:
    - vars/apache.yml
    - vars/php.yml
    - vars/app.yml

  vars:
    php_default_version_debian: "{{ php_version }}"

    php_enable_php_fpm: true

    php_fpm_pool_user: "{{ username }}"

    php_fpm_pool_group: "{{ username }}"

    php_fpm_pools:
      - pool_name: "{{ username }}"
        pool_listen: "/run/php/{{ username }}.sock"
        pool_listen_allowed_clients: "127.0.0.1"
        pool_pm: dynamic
        pool_pm_max_children: 5
        pool_pm_start_servers: 2
        pool_pm_min_spare_servers: 1
        pool_pm_max_spare_servers: 3
        pool_pm_max_requests: 500
        pool_pm_status_path: /status

    apache_global_vhost_settings: ""

    apache_vhosts_filename: "{{ username }}.conf"

    apache_vhosts:
      - servername: "{{ domainname }}"
        serveralias: "{{ domainalias }}"
        documentroot: "{{ apache_root_path }}/public"
        apache_allow_override: "Limit Options FileInfo"
        apache_options: "FollowSymLinks"
        apache_directory_index: "index.php"
        directory_list:
          - path: "{{ apache_root_path }}/public/wp-content"
            options: "FollowSymLinks"

        extra_parameters: |
          AssignUserID {{ username }} {{ username }}

          <FilesMatch ".+\.ph(ar|p|tml)$">
              {% if php_version == "8.0" %}
                  SetHandler "proxy:unix:/run/php/{{ username }}.sock|fcgi://php80.localhost"
              {% elif php_version == "8.1" %}
                  SetHandler "proxy:unix:/run/php/{{ username }}.sock|fcgi://php81.localhost"
              {% elif php_version == "8.2" %}
                  SetHandler "proxy:unix:/run/php/{{ username }}.sock|fcgi://php82.localhost"
              {% elif php_version == "8.3" %}
                  SetHandler "proxy:unix:/run/php/{{ username }}.sock|fcgi://php83.localhost"
              {% endif %}
          </FilesMatch>

          <IfModule mod_setenvif.c>
              SetEnvIf X-Forwarded-Proto "^https$" HTTPS
          </IfModule>

          <IfModule mod_headers.c>
              Header always append X-Frame-Options DENY
              Header set X-Content-Type-Options nosniff
              Header set X-Permitted-Cross-Domain-Policies "none"
              Header set Referrer-Policy "same-origin"
              Header set Cache-Control "no-store"
              Header set X-XSS-Protection "1; mode=block"
          </IfModule>

          ErrorLog {{ apache_logs_path }}/error.log
          CustomLog {{ apache_logs_path }}/access.log combined

    logrotate_scripts:
      - name: "{{ username }}"
        path: "{{ wordpress_logs_path }}/*.log"
        options:
          - daily
          - missingok
          - rotate 3
          - compress
          - delaycompress
          - notifempty
          - create 666 {{ username }} {{ username }}

  roles:
    - farisc0de.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - clonerepo
    - wordpress
    - logrotate
