---
- hosts: all
  vars:
    - application_type: "phpapp"
  vars_files:
    - "{{ hostname }}.yml"
    - "vault/{{ hostname }}.yml"
  roles:
    - common
    - securitybaseline
    - apache
    - php
    - phpapp
