---
- name: Deploy WordPress
  hosts: all
  vars_prompt:
    # Linux user
    - name: "username"
      prompt: "Enter the username"
      private: false

    - name: "groupname"
      prompt: "Enter the groupname"
      private: false

    # Virtual host
    - name: "domainname"
      prompt: "Enter the domainname"
      private: false

    - name: "domainalias"
      prompt: "Enter the domainalias"
      private: false

    # Database
    - name: "laravel_db_host"
      prompt: "Enter the database host"
      private: false

    - name: "laravel_db_name"
      prompt: "Enter the database name"
      private: false

    - name: "laravel_db_user"
      prompt: "Enter the database user"
      private: false

    - name: "laravel_db_password"
      prompt: "Enter the database password"
      private: true

    - name: "laravel_smtp_host"
      prompt: "Enter the smtp host"
      private: false

    - name: "laravel_smtp_port"
      prompt: "Enter the smtp port"
      private: false
      default: "587"

    - name: "laravel_smtp_username"
      prompt: "Enter the smtp username"
      private: false

    - name: "laravel_smtp_password"
      prompt: "Enter the smtp password"
      private: true

    - name: "laravel_smtp_encryption"
      prompt: "Enter the smtp encryption"
      private: false
      default: "tls"

    - name: "laravel_smtp_from_address"
      prompt: "Enter the smtp from address"
      private: false

    # Project Repo
    - name: "project_name"
      prompt: "Enter the project name"
      private: false

    - name: "git_repo"
      prompt: "Enter the git repository"
      private: false

    - name: "git_branch"
      prompt: "Enter the git branch"
      private: false

    # Azure DevOps
    - name: "my_az_devops_agent_name"
      prompt: "Enter Azure DevOps the agent name"
      private: false

    - name: "az_devops_accesstoken"
      prompt: "Enter the agent token"
      private: true

    - name: "az_devops_deployment_group_name"
      prompt: "Enter the agent deployment group name"
      private: false

    - name: "az_devops_project_name"
      prompt: "Enter the agent deployment group project name"
      private: false

  vars_files:
    - vars/apache.yml
    - vars/php.yml
    - vars/app.yml

  vars:
    php_default_version_debian: "{{ php_version }}"

    php_enable_php_fpm: true

    php_fpm_pools:
      - pool_name: "{{ username }}"
        php_fpm_pool_user: "{{ username }}"
        php_fpm_pool_group: "{{ username }}"
        pool_listen: "/run/php/{{ username }}.sock"
        pool_listen_allowed_clients: "127.0.0.1"
        pool_pm: dynamic
        pool_pm_max_children: 5
        pool_pm_start_servers: 2
        pool_pm_min_spare_servers: 1
        pool_pm_max_spare_servers: 3
        pool_pm_max_requests: 500

    apache_global_vhost_settings: ""

    apache_vhosts_filename: "{{ username }}.conf"

    apache_vhosts:
      - servername: "{{ domainname }}"
        serveralias: "{{ domainalias }}"
        documentroot: "{{ apache_root_path }}/{{ project_name }}/public"
        apache_allow_override: "All"
        apache_options: "FollowSymLinks"

        extra_parameters: |
          AssignUserID {{ username }} {{ username }}

          <FilesMatch ".+\.ph(ar|p|tml)$">
              {% if php_version == 8.0 %}
                  SetHandler "proxy:unix:/run/php/{{ username }}.sock|fcgi://php80.localhost"
              {% elif php_version == 8.1 %}
                  SetHandler "proxy:unix:/run/php/{{ username }}.sock|fcgi://php81.localhost"
              {% elif php_version == 8.2 %}
                  SetHandler "proxy:unix:/run/php/{{ username }}.sock|fcgi://php82.localhost"
              {% elif php_version == 8.3 %}
                  SetHandler "proxy:unix:/run/php/{{ username }}.sock|fcgi://php83.localhost"
              {% endif %}
          </FilesMatch>

          <IfModule mod_headers.c>
              Header always append X-Frame-Options DENY
              Header set X-Content-Type-Options nosniff
              Header set X-Permitted-Cross-Domain-Policies "none"
              Header set Referrer-Policy "same-origin"
              Header set Cache-Control "no-store"
              Header set X-XSS-Protection "1; mode=block"
          </IfModule>

          <IfModule mod_setenvif.c>
              SetEnvIf X-Forwarded-Proto "^https$" HTTPS
          </IfModule>

          ErrorLog {{ apache_logs_path }}/error.log
          CustomLog {{ apache_logs_path }}/access.log combined

    az_devops_agent_role: "deployment"

    az_devops_agent_user: "{{ username }}"

    az_devops_agent_group: "{{ username }}"

    az_devops_agent_name: "{{ my_az_devops_agent_name }}"

    az_devops_agent_replace_existing: true

    az_devops_accountname: "farisc0de"

  roles:
    - farisc0de.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - farisc0de.az_devops
    - geerlingguy.composer
    - clonerepo
    - laravel
