---
- name: Install Azure DevOps Agent
  hosts: all
  vars_prompt:
    - name: "username"
      prompt: "Enter the username"
      private: false

    - name: "az_devops_agent_name"
      prompt: "Enter Azure DevOps the agent name"
      private: false

    - name: "az_devops_deployment_group_name"
      prompt: "Enter the agent deployment group name"
      private: false

    - name: "az_devops_project_name"
      prompt: "Enter the agent deployment group project name"
      private: false

  vars:
    az_devops_agent_user: "{{ username }}"
    az_devops_agent_group: "{{ username }}"
    az_devops_agent_role: "deployment"
    az_devops_accountname: "farisc0de"
    az_agent_auth_type: "PAT"

  vars_files: vault/personal_access_token.yml

  roles:
    - farisc0de.az_devops
