- name: Install Security Patch
  hosts: all
  vars:
    unattended_origins_patterns:
      - "origin=Ubuntu,archive=${distro_codename}-security"
    unattended_mail: ""

  roles:
    - hifis.toolkit.unattended_upgrades
